// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: orchestrator_listener.proto

package pb

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// Orchestrator_ListenerClient is the client API for Orchestrator_Listener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Orchestrator_ListenerClient interface {
}

type orchestrator_ListenerClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestrator_ListenerClient(cc grpc.ClientConnInterface) Orchestrator_ListenerClient {
	return &orchestrator_ListenerClient{cc}
}

// Orchestrator_ListenerServer is the server API for Orchestrator_Listener service.
// All implementations must embed UnimplementedOrchestrator_ListenerServer
// for forward compatibility.
type Orchestrator_ListenerServer interface {
	mustEmbedUnimplementedOrchestrator_ListenerServer()
}

// UnimplementedOrchestrator_ListenerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestrator_ListenerServer struct{}

func (UnimplementedOrchestrator_ListenerServer) mustEmbedUnimplementedOrchestrator_ListenerServer() {}
func (UnimplementedOrchestrator_ListenerServer) testEmbeddedByValue()                               {}

// UnsafeOrchestrator_ListenerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Orchestrator_ListenerServer will
// result in compilation errors.
type UnsafeOrchestrator_ListenerServer interface {
	mustEmbedUnimplementedOrchestrator_ListenerServer()
}

func RegisterOrchestrator_ListenerServer(s grpc.ServiceRegistrar, srv Orchestrator_ListenerServer) {
	// If the following call pancis, it indicates UnimplementedOrchestrator_ListenerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Orchestrator_Listener_ServiceDesc, srv)
}

// Orchestrator_Listener_ServiceDesc is the grpc.ServiceDesc for Orchestrator_Listener service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Orchestrator_Listener_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Orchestrator_Listener",
	HandlerType: (*Orchestrator_ListenerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "orchestrator_listener.proto",
}
