services:
  orchestrator:
    container_name: orchestrator
    build:
      context: ./services/orchestrator
    networks:
      internal:
        ipv4_address: 10.0.0.10

  agent:
    container_name: agent
    build:
      context: ./services/agent

networks:
  internal:
    ipam:
      config:
        - subnet: 10.0.0.0/24
