// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: filesystem.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Child struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to DirORContent:
	//
	//	*Child_Dir
	//	*Child_Content
	DirORContent  isChild_DirORContent `protobuf_oneof:"DirORContent"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Child) Reset() {
	*x = Child{}
	mi := &file_filesystem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Child) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Child) ProtoMessage() {}

func (x *Child) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Child.ProtoReflect.Descriptor instead.
func (*Child) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{0}
}

func (x *Child) GetDirORContent() isChild_DirORContent {
	if x != nil {
		return x.DirORContent
	}
	return nil
}

func (x *Child) GetDir() *Dir {
	if x != nil {
		if x, ok := x.DirORContent.(*Child_Dir); ok {
			return x.Dir
		}
	}
	return nil
}

func (x *Child) GetContent() []byte {
	if x != nil {
		if x, ok := x.DirORContent.(*Child_Content); ok {
			return x.Content
		}
	}
	return nil
}

type isChild_DirORContent interface {
	isChild_DirORContent()
}

type Child_Dir struct {
	Dir *Dir `protobuf:"bytes,1,opt,name=dir,proto3,oneof"`
}

type Child_Content struct {
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3,oneof"`
}

func (*Child_Dir) isChild_DirORContent() {}

func (*Child_Content) isChild_DirORContent() {}

type Dir struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Children      map[string]*Child      `protobuf:"bytes,1,rep,name=children,proto3" json:"children,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dir) Reset() {
	*x = Dir{}
	mi := &file_filesystem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dir) ProtoMessage() {}

func (x *Dir) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dir.ProtoReflect.Descriptor instead.
func (*Dir) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{1}
}

func (x *Dir) GetChildren() map[string]*Child {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_filesystem_proto protoreflect.FileDescriptor

var file_filesystem_proto_rawDesc = string([]byte{
	0x0a, 0x10, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x50, 0x0a, 0x05, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x12,
	0x1b, 0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x70,
	0x62, 0x2e, 0x44, 0x69, 0x72, 0x48, 0x00, 0x52, 0x03, 0x64, 0x69, 0x72, 0x12, 0x1a, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x0e, 0x0a, 0x0c, 0x44, 0x69, 0x72, 0x4f,
	0x52, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x80, 0x01, 0x0a, 0x03, 0x44, 0x69, 0x72,
	0x12, 0x31, 0x0a, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x69, 0x72, 0x2e, 0x43, 0x68, 0x69, 0x6c,
	0x64, 0x72, 0x65, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64,
	0x72, 0x65, 0x6e, 0x1a, 0x46, 0x0a, 0x0d, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x69, 0x6c, 0x64,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x29, 0x5a, 0x27, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x65, 0x63, 0x6b, 0x65, 0x72,
	0x36, 0x33, 0x2f, 0x73, 0x69, 0x6d, 0x74, 0x72, 0x69, 0x63, 0x6b, 0x79, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_filesystem_proto_rawDescOnce sync.Once
	file_filesystem_proto_rawDescData []byte
)

func file_filesystem_proto_rawDescGZIP() []byte {
	file_filesystem_proto_rawDescOnce.Do(func() {
		file_filesystem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_filesystem_proto_rawDesc), len(file_filesystem_proto_rawDesc)))
	})
	return file_filesystem_proto_rawDescData
}

var file_filesystem_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_filesystem_proto_goTypes = []any{
	(*Child)(nil), // 0: pb.Child
	(*Dir)(nil),   // 1: pb.Dir
	nil,           // 2: pb.Dir.ChildrenEntry
}
var file_filesystem_proto_depIdxs = []int32{
	1, // 0: pb.Child.dir:type_name -> pb.Dir
	2, // 1: pb.Dir.children:type_name -> pb.Dir.ChildrenEntry
	0, // 2: pb.Dir.ChildrenEntry.value:type_name -> pb.Child
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_filesystem_proto_init() }
func file_filesystem_proto_init() {
	if File_filesystem_proto != nil {
		return
	}
	file_filesystem_proto_msgTypes[0].OneofWrappers = []any{
		(*Child_Dir)(nil),
		(*Child_Content)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_filesystem_proto_rawDesc), len(file_filesystem_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_filesystem_proto_goTypes,
		DependencyIndexes: file_filesystem_proto_depIdxs,
		MessageInfos:      file_filesystem_proto_msgTypes,
	}.Build()
	File_filesystem_proto = out.File
	file_filesystem_proto_goTypes = nil
	file_filesystem_proto_depIdxs = nil
}
