// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: machine_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Runner int32

const (
	Runner_Binary Runner = 0
	Runner_Java   Runner = 1
)

// Enum value maps for Runner.
var (
	Runner_name = map[int32]string{
		0: "Binary",
		1: "Java",
	}
	Runner_value = map[string]int32{
		"Binary": 0,
		"Java":   1,
	}
)

func (x Runner) Enum() *Runner {
	p := new(Runner)
	*p = x
	return p
}

func (x Runner) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Runner) Descriptor() protoreflect.EnumDescriptor {
	return file_machine_service_proto_enumTypes[0].Descriptor()
}

func (Runner) Type() protoreflect.EnumType {
	return &file_machine_service_proto_enumTypes[0]
}

func (x Runner) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Runner.Descriptor instead.
func (Runner) EnumDescriptor() ([]byte, []int) {
	return file_machine_service_proto_rawDescGZIP(), []int{0}
}

type Sucess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sucess        bool                   `protobuf:"varint,1,opt,name=sucess,proto3" json:"sucess,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sucess) Reset() {
	*x = Sucess{}
	mi := &file_machine_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sucess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sucess) ProtoMessage() {}

func (x *Sucess) ProtoReflect() protoreflect.Message {
	mi := &file_machine_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sucess.ProtoReflect.Descriptor instead.
func (*Sucess) Descriptor() ([]byte, []int) {
	return file_machine_service_proto_rawDescGZIP(), []int{0}
}

func (x *Sucess) GetSucess() bool {
	if x != nil {
		return x.Sucess
	}
	return false
}

type StartStopReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     uint32                 `protobuf:"varint,1,opt,name=Machine_id,json=MachineId,proto3" json:"Machine_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartStopReq) Reset() {
	*x = StartStopReq{}
	mi := &file_machine_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartStopReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartStopReq) ProtoMessage() {}

func (x *StartStopReq) ProtoReflect() protoreflect.Message {
	mi := &file_machine_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartStopReq.ProtoReflect.Descriptor instead.
func (*StartStopReq) Descriptor() ([]byte, []int) {
	return file_machine_service_proto_rawDescGZIP(), []int{1}
}

func (x *StartStopReq) GetMachineId() uint32 {
	if x != nil {
		return x.MachineId
	}
	return 0
}

type ConfigReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     uint32                 `protobuf:"varint,1,opt,name=Machine_id,json=MachineId,proto3" json:"Machine_id,omitempty"`
	Runner        Runner                 `protobuf:"varint,2,opt,name=Runner,proto3,enum=pb.Runner" json:"Runner,omitempty"`
	BinaryPath    string                 `protobuf:"bytes,3,opt,name=BinaryPath,proto3" json:"BinaryPath,omitempty"`
	RemoteZip     *string                `protobuf:"bytes,4,opt,name=RemoteZip,proto3,oneof" json:"RemoteZip,omitempty"`
	Files         *Dir                   `protobuf:"bytes,5,opt,name=Files,proto3,oneof" json:"Files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigReq) Reset() {
	*x = ConfigReq{}
	mi := &file_machine_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigReq) ProtoMessage() {}

func (x *ConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_machine_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigReq.ProtoReflect.Descriptor instead.
func (*ConfigReq) Descriptor() ([]byte, []int) {
	return file_machine_service_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigReq) GetMachineId() uint32 {
	if x != nil {
		return x.MachineId
	}
	return 0
}

func (x *ConfigReq) GetRunner() Runner {
	if x != nil {
		return x.Runner
	}
	return Runner_Binary
}

func (x *ConfigReq) GetBinaryPath() string {
	if x != nil {
		return x.BinaryPath
	}
	return ""
}

func (x *ConfigReq) GetRemoteZip() string {
	if x != nil && x.RemoteZip != nil {
		return *x.RemoteZip
	}
	return ""
}

func (x *ConfigReq) GetFiles() *Dir {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_machine_service_proto protoreflect.FileDescriptor

var file_machine_service_proto_rawDesc = string([]byte{
	0x0a, 0x15, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x10, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x20, 0x0a,
	0x06, 0x53, 0x75, 0x63, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x75, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x75, 0x63, 0x65, 0x73, 0x73, 0x22,
	0x2e, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x74, 0x6f, 0x70, 0x5f, 0x72, 0x65, 0x71,
	0x12, 0x1d, 0x0a, 0x0a, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x22,
	0xce, 0x01, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x1d,
	0x0a, 0x0a, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x22, 0x0a,
	0x06, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x06, 0x52, 0x75, 0x6e, 0x6e, 0x65,
	0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x50, 0x61, 0x74, 0x68, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x50, 0x61, 0x74,
	0x68, 0x12, 0x21, 0x0a, 0x09, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5a, 0x69, 0x70, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5a, 0x69,
	0x70, 0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x69, 0x72, 0x48, 0x01, 0x52, 0x05,
	0x46, 0x69, 0x6c, 0x65, 0x73, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x52, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x5a, 0x69, 0x70, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x46, 0x69, 0x6c, 0x65, 0x73,
	0x2a, 0x1e, 0x0a, 0x06, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x69,
	0x6e, 0x61, 0x72, 0x79, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x61, 0x76, 0x61, 0x10, 0x01,
	0x32, 0xb0, 0x01, 0x0a, 0x06, 0x74, 0x72, 0x69, 0x63, 0x6b, 0x79, 0x12, 0x26, 0x0a, 0x05, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53,
	0x74, 0x6f, 0x70, 0x5f, 0x72, 0x65, 0x71, 0x1a, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x75, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x25, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x11, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x74, 0x6f, 0x70, 0x5f, 0x72, 0x65, 0x71, 0x1a, 0x0a,
	0x2e, 0x70, 0x62, 0x2e, 0x53, 0x75, 0x63, 0x65, 0x73, 0x73, 0x12, 0x2a, 0x0a, 0x0c, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x0e, 0x2e, 0x70, 0x62, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x72, 0x65, 0x71, 0x1a, 0x0a, 0x2e, 0x70, 0x62, 0x2e,
	0x53, 0x75, 0x63, 0x65, 0x73, 0x73, 0x12, 0x2b, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x5f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x5f, 0x72, 0x65, 0x71, 0x1a, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x75, 0x63,
	0x65, 0x73, 0x73, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x62, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x36, 0x33, 0x2f, 0x73, 0x69, 0x6d, 0x74, 0x72,
	0x69, 0x63, 0x6b, 0x79, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_machine_service_proto_rawDescOnce sync.Once
	file_machine_service_proto_rawDescData []byte
)

func file_machine_service_proto_rawDescGZIP() []byte {
	file_machine_service_proto_rawDescOnce.Do(func() {
		file_machine_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_machine_service_proto_rawDesc), len(file_machine_service_proto_rawDesc)))
	})
	return file_machine_service_proto_rawDescData
}

var file_machine_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_machine_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_machine_service_proto_goTypes = []any{
	(Runner)(0),          // 0: pb.Runner
	(*Sucess)(nil),       // 1: pb.Sucess
	(*StartStopReq)(nil), // 2: pb.StartStop_req
	(*ConfigReq)(nil),    // 3: pb.Config_req
	(*Dir)(nil),          // 4: pb.Dir
}
var file_machine_service_proto_depIdxs = []int32{
	0, // 0: pb.Config_req.Runner:type_name -> pb.Runner
	4, // 1: pb.Config_req.Files:type_name -> pb.Dir
	2, // 2: pb.tricky.Start:input_type -> pb.StartStop_req
	2, // 3: pb.tricky.Stop:input_type -> pb.StartStop_req
	3, // 4: pb.tricky.ChangeConfig:input_type -> pb.Config_req
	3, // 5: pb.tricky.Create_Server:input_type -> pb.Config_req
	1, // 6: pb.tricky.Start:output_type -> pb.Sucess
	1, // 7: pb.tricky.Stop:output_type -> pb.Sucess
	1, // 8: pb.tricky.ChangeConfig:output_type -> pb.Sucess
	1, // 9: pb.tricky.Create_Server:output_type -> pb.Sucess
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_machine_service_proto_init() }
func file_machine_service_proto_init() {
	if File_machine_service_proto != nil {
		return
	}
	file_filesystem_proto_init()
	file_machine_service_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_machine_service_proto_rawDesc), len(file_machine_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_machine_service_proto_goTypes,
		DependencyIndexes: file_machine_service_proto_depIdxs,
		EnumInfos:         file_machine_service_proto_enumTypes,
		MessageInfos:      file_machine_service_proto_msgTypes,
	}.Build()
	File_machine_service_proto = out.File
	file_machine_service_proto_goTypes = nil
	file_machine_service_proto_depIdxs = nil
}
